USE jonggies_waffle;

CREATE TABLE IF NOT EXISTS satisfaction_photos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  customer_name VARCHAR(60) NOT NULL,
  caption VARCHAR(120) DEFAULT '',
  image VARCHAR(255) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
